spring.application.name=quantity-measurement-app
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/quantitymeasurementdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.com.quantity.measurement=INFO
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
